"""
AI Test Platform — Streamlit Test Review Interface

Allows users to upload generated Markdown test specs, manually edit them,
download the result, and parse them back to structured JSON via the backend API.
"""

import streamlit as st
import requests

# Backend API endpoint for test validation & parsing
API_URL = "http://127.0.0.1:8000/api/v1/review/upload"

# ── Page Config ───────────────────────────────────────────────────
st.set_page_config(
    page_title="AI Test Reviewer",
    page_icon="🧪",
    layout="wide",
)

# ── Sidebar ───────────────────────────────────────────────────────
with st.sidebar:
    st.header("🧪 Test Reviewer")
    st.markdown("""
**Workflow:**
1. Upload or paste a `.md` test spec
2. Edit test cases inline
3. Download the revised file
4. Validate & convert to JSON
""")
    st.divider()
    st.caption("Format each test case as:")
    st.code("### Test Case Name\n**Target**: POST /endpoint\n**Input**: payload\n**Expected**: 200 OK", language="markdown")

st.title("🧪 AI Test Case Review Interface")
st.markdown(
    "Upload a `.md` test specification generated by the AI pipeline, "
    "review and edit the cases, then convert to structured JSON for execution."
)

st.divider()

# ── State Management ──────────────────────────────────────────────
DEFAULT_MD = """# Comprehensive Test Specification

## Functional Tests

### Test Case 1: Valid Login
**Target**: `POST /login`
**Input**: username=admin, password=correct
**Expected**: 200 OK

## Negative Tests

### Test Case 2: Invalid Password
**Target**: `POST /login`
**Input**: username=admin, password=wrong
**Expected**: 401 Unauthorized
"""

if "markdown_content" not in st.session_state:
    st.session_state.markdown_content = DEFAULT_MD

# ── 1. File Upload ────────────────────────────────────────────────
st.subheader("① Upload Generated Tests")
uploaded_file = st.file_uploader("Upload an existing Markdown test file (.md)", type=["md"])

if uploaded_file is not None:
    try:
        content = uploaded_file.getvalue().decode("utf-8")
        st.session_state.markdown_content = content
        st.success(f"Loaded **{uploaded_file.name}** successfully.")
    except Exception as e:
        st.error(f"Failed to read file: {e}")

st.divider()

# ── 2. Editor & Preview columns ───────────────────────────────────
col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.subheader("② Edit Test Specification")

    edited_markdown = st.text_area(
        "Make your necessary QA adjustments below:",
        value=st.session_state.markdown_content,
        height=450,
        label_visibility="collapsed",
    )

    col1_a, col1_b = st.columns(2)
    with col1_a:
        st.download_button(
            label="💾 Download Edited .md",
            data=edited_markdown.encode("utf-8"),
            file_name="reviewed_tests.md",
            mime="text/markdown",
            use_container_width=True,
        )
    with col1_b:
        run_parse = st.button("🚀 Validate & Convert to JSON", use_container_width=True)


with col2:
    st.subheader("③ Parsed JSON Structure")

    if run_parse:
        with st.spinner("Sending to backend for validation…"):
            files = {"file": ("tests.md", edited_markdown.encode("utf-8"), "text/markdown")}
            try:
                response = requests.post(API_URL, files=files, timeout=10)

                if response.status_code == 200:
                    data = response.json()
                    st.session_state.parsed_cases = data["test_cases"]
                    st.session_state.parsed_count = data["parsed_count"]
                    st.session_state.reviewed_md = edited_markdown
                else:
                    error_msg = response.json().get("detail", response.text)
                    st.error("❌ Validation Failed")
                    st.warning(error_msg)
                    st.info(
                        "💡 Each test case must have a `### Heading`, "
                        "then `**Target**:`, `**Input**:`, and `**Expected**:` lines."
                    )

            except requests.exceptions.ConnectionError:
                st.error("❌ Backend not reachable.")
                st.code("cd backend && uvicorn main:app --reload")
            except requests.exceptions.Timeout:
                st.error("❌ Request timed out. Is the backend overloaded?")

    if "parsed_cases" in st.session_state:
        st.success(f"✅ Extracted **{st.session_state.parsed_count}** test cases.")
        
        # execution section
        project_id = st.session_state.get("project_id", "test_project_id")
        
        if st.button("🔥 Execute Tests in Sandbox", type="primary", use_container_width=True):
            exec_url = f"http://127.0.0.1:8000/api/v1/tests/execute/{project_id}"
            with st.spinner("Initiating backend execution..."):
                try:
                    payload = {"markdown_content": st.session_state.reviewed_md, "with_coverage": True}
                    req = requests.post(exec_url, json=payload)
                    if req.status_code == 202:
                        st.success("Execution Task Queued! Switch to Dashboard to view live results.")
                    else:
                        st.error(f"Execution failed to start: {req.text}")
                except Exception as e:
                    st.error(f"Error calling execution API: {e}")
                    
        with st.expander("View JSON payload", expanded=False):
            st.json(st.session_state.parsed_cases)
    else:
        st.info("Click **Validate & Convert to JSON** to parse the Markdown.")

