"""
AI Test Platform — pytest Runner

Executes generated test files using pytest in a subprocess.
Parses results from JSON report output.
"""

import json
import subprocess
import tempfile
import sys
import os
from pathlib import Path
from dataclasses import dataclass, field

from utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class IndividualTestResult:
    """Result of a single test case."""
    nodeid: str
    outcome: str  # "passed", "failed", "error", "skipped"
    duration: float = 0.0
    stdout: str = ""
    stderr: str = ""
    longrepr: str = ""  # Failure representation


@dataclass
class PytestRunResult:
    """Aggregated result of a pytest run."""
    total: int = 0
    passed: int = 0
    failed: int = 0
    errors: int = 0
    skipped: int = 0
    duration: float = 0.0
    results: list[IndividualTestResult] = field(default_factory=list)
    raw_output: str = ""
    success: bool = False


class PytestRunner:
    """
    Programmatically executes pytest and collects results.

    Uses pytest-json-report for structured output parsing.
    """

    def run_tests(
        self,
        test_dir: Path,
        project_dir: Path | None = None,
        with_coverage: bool = False,
        timeout: int = 300,
        use_pytest_main: bool = True,
    ) -> PytestRunResult:
        """
        Execute pytest on the given test directory.

        Args:
            test_dir: Directory containing test files
            project_dir: Project root for coverage (optional)
            with_coverage: Enable coverage reporting
            timeout: Maximum execution time in seconds

        Returns:
            PytestRunResult with aggregated and individual results
        """
        # Create a temp file for JSON report
        report_file = Path(tempfile.mktemp(suffix=".json"))

        # Build pytest command
        cmd = [
            str(test_dir),
            f"--json-report-file={report_file}",
            "--json-report",
            "-v",
            "--tb=short",
        ]

        if with_coverage and project_dir:
            cmd.extend([
                f"--cov={project_dir}",
                "--cov-report=json",
            ])

        pytest_cmd = [sys.executable, "-m", "pytest"] + cmd

        logger.info("Running pytest", cmd=" ".join(pytest_cmd), test_dir=str(test_dir), use_pytest_main=use_pytest_main)

        try:
            if use_pytest_main:
                import pytest
                start_cwd = os.getcwd()
                os.chdir(str(project_dir or test_dir.parent))
                try:
                    result_code = pytest.main(cmd)
                    raw_output = f"pytest.main exit code: {result_code}"
                finally:
                    os.chdir(start_cwd)

                # Parse JSON report generated by pytest-json-report plugin
                if report_file.exists():
                    result = self._parse_json_report(report_file, raw_output)
                else:
                    result = PytestRunResult(
                        raw_output=raw_output,
                        success=(result_code == 0)
                    )
            else:
                process = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=timeout,
                    cwd=str(project_dir or test_dir.parent),
                )

                raw_output = process.stdout + process.stderr

                # Parse JSON report
                if report_file.exists():
                    result = self._parse_json_report(report_file, raw_output)
                else:
                    result = self._parse_raw_output(process, raw_output)

            logger.info(
                "Pytest execution completed",
                total=result.total,
                passed=result.passed,
                failed=result.failed,
                errors=result.errors,
                duration=result.duration,
            )
            return result

        except subprocess.TimeoutExpired:
            logger.error("Pytest execution timed out", timeout=timeout)
            return PytestRunResult(
                raw_output=f"Execution timed out after {timeout}s",
                success=False,
            )
        except Exception as e:
            logger.error("Pytest execution failed", error=str(e))
            return PytestRunResult(raw_output=str(e), success=False)
        finally:
            if report_file.exists():
                report_file.unlink()

    def _parse_json_report(self, report_file: Path, raw_output: str) -> PytestRunResult:
        """Parse pytest-json-report output."""
        with open(report_file, "r") as f:
            report = json.load(f)

        summary = report.get("summary", {})
        tests = report.get("tests", [])

        results = []
        for test in tests:
            results.append(IndividualTestResult(
                nodeid=test.get("nodeid", ""),
                outcome=test.get("outcome", "unknown"),
                duration=test.get("duration", 0.0),
                stdout=test.get("setup", {}).get("stdout", "") +
                       test.get("call", {}).get("stdout", ""),
                stderr=test.get("setup", {}).get("stderr", "") +
                       test.get("call", {}).get("stderr", ""),
                longrepr=test.get("call", {}).get("longrepr", ""),
            ))

        return PytestRunResult(
            total=summary.get("total", 0),
            passed=summary.get("passed", 0),
            failed=summary.get("failed", 0),
            errors=summary.get("error", 0),
            skipped=summary.get("skipped", 0),
            duration=report.get("duration", 0.0),
            results=results,
            raw_output=raw_output,
            success=summary.get("failed", 0) == 0 and summary.get("error", 0) == 0,
        )

    def _parse_raw_output(self, process: subprocess.CompletedProcess, raw_output: str) -> PytestRunResult:
        """Fallback: parse raw pytest output when JSON report is unavailable."""
        return PytestRunResult(
            raw_output=raw_output,
            success=process.returncode == 0,
        )
